
(in-package :modf)

(define-modf-rewrite caar (expr)
  `(car (car ,(second expr))) )
(define-modf-rewrite cadr (expr)
  `(car (cdr ,(second expr))) )
(define-modf-rewrite cdar (expr)
  `(cdr (car ,(second expr))) )
(define-modf-rewrite cddr (expr)
  `(cdr (cdr ,(second expr))) )

(define-modf-rewrite caaar (expr)
  `(car (car (car ,(second expr)))) )
(define-modf-rewrite caadr (expr)
  `(car (car (cdr ,(second expr)))) )
(define-modf-rewrite cadar (expr)
  `(car (cdr (car ,(second expr)))) )
(define-modf-rewrite cdaar (expr)
  `(cdr (car (car ,(second expr)))) )
(define-modf-rewrite caddr (expr)
  `(car (cdr (cdr ,(second expr)))) )
(define-modf-rewrite cdadr (expr)
  `(cdr (car (cdr ,(second expr)))) )
(define-modf-rewrite cddar (expr)
  `(cdr (cdr (car ,(second expr)))) )
(define-modf-rewrite cdddr (expr)
  `(cdr (cdr (cdr ,(second expr)))) )

(define-modf-rewrite caaaar (expr)
  `(car (car (car (car ,(second expr))))) )
(define-modf-rewrite caaadr (expr)
  `(car (car (car (cdr ,(second expr))))) )
(define-modf-rewrite caadar (expr)
  `(car (car (cdr (car ,(second expr))))) )
(define-modf-rewrite cadaar (expr)
  `(car (cdr (car (car ,(second expr))))) )
(define-modf-rewrite cdaaar (expr)
  `(cdr (car (car (car ,(second expr))))) )

(define-modf-rewrite caaddr (expr)
  `(car (car (cdr (cdr ,(second expr))))) )
(define-modf-rewrite cadadr (expr)
  `(car (cdr (car (cdr ,(second expr))))) )
(define-modf-rewrite cdaadr (expr)
  `(cdr (car (car (cdr ,(second expr))))) )
(define-modf-rewrite caddar (expr)
  `(car (cdr (cdr (car ,(second expr))))) )
(define-modf-rewrite cdadar (expr)
  `(cdr (car (cdr (car ,(second expr))))) )
(define-modf-rewrite cddaar (expr)
  `(cdr (cdr (car (car ,(second expr))))) )

(define-modf-rewrite cdddar (expr)
  `(cdr (cdr (cdr (car ,(second expr))))) )
(define-modf-rewrite cddadr (expr)
  `(cdr (cdr (car (cdr ,(second expr))))) )
(define-modf-rewrite cdaddr (expr)
  `(cdr (car (cdr (cdr ,(second expr))))) )
(define-modf-rewrite cadddr (expr)
  `(car (cdr (cdr (cdr ,(second expr))))) )

(define-modf-rewrite cddddr (expr)
  `(cdr (cdr (cdr (cdr ,(second expr))))) )

(define-modf-rewrite first (expr)
  `(car ,(second expr)) )
(define-modf-rewrite second (expr)
  `(cadr ,(second expr)) )
(define-modf-rewrite third (expr)
  `(caddr ,(second expr)) )
(define-modf-rewrite fourth (expr)
  `(cadddr ,(second expr)) )
(define-modf-rewrite fifth (expr)
  `(car (cddddr ,(second expr))) )
(define-modf-rewrite sixth (expr)
  `(cadr (cddddr ,(second expr))) )
(define-modf-rewrite seventh (expr)
  `(caddr (cddddr ,(second expr))) )
(define-modf-rewrite eighth (expr)
  `(cadddr (cddddr ,(second expr))) )
(define-modf-rewrite ninth (expr)
  `(car (cddddr (cddddr ,(second expr)))) )
(define-modf-rewrite tenth (expr)
  `(cadr (cddddr (cddddr ,(second expr)))) )
