
(in-package :modf)

(define-modf-rewrite caar (expr)
  `(car (car ,(second expr))) )
(define-modf-rewrite cadr (expr)
  `(car (cdr ,(second expr))) )
(define-modf-rewrite cdar (expr)
  `(cdr (car ,(second expr))) )
(define-modf-rewrite cddr (expr)
  `(cdr (cdr ,(second expr))) )

(define-modf-rewrite caaar (expr)
  `(car (caar ,(second expr))) )
(define-modf-rewrite caadr (expr)
  `(car (cadr ,(second expr))) )
(define-modf-rewrite cadar (expr)
  `(car (cdar ,(second expr))) )
(define-modf-rewrite cdaar (expr)
  `(cdr (caar ,(second expr))) )
(define-modf-rewrite caddr (expr)
  `(car (cddr ,(second expr))) )
(define-modf-rewrite cdadr (expr)
  `(cdr (cadr ,(second expr))) )
(define-modf-rewrite cddar (expr)
  `(cdr (cdar ,(second expr))) )
(define-modf-rewrite cdddr (expr)
  `(cdr (cddr ,(second expr))) )

(define-modf-rewrite caaaar (expr)
  `(car (caaar ,(second expr))) )
(define-modf-rewrite caaadr (expr)
  `(car (caadr ,(second expr))) )
(define-modf-rewrite caadar (expr)
  `(car (cadar ,(second expr))) )
(define-modf-rewrite cadaar (expr)
  `(car (cdaar ,(second expr))) )
(define-modf-rewrite cdaaar (expr)
  `(cdr (caaar ,(second expr))) )

(define-modf-rewrite caaddr (expr)
  `(car (caddr ,(second expr))) )
(define-modf-rewrite cadadr (expr)
  `(car (cdadr ,(second expr))) )
(define-modf-rewrite cdaadr (expr)
  `(cdr (caadr ,(second expr))) )
(define-modf-rewrite caddar (expr)
  `(car (cddar ,(second expr))) )
(define-modf-rewrite cdadar (expr)
  `(cdr (cadar ,(second expr))) )
(define-modf-rewrite cddaar (expr)
  `(cdr (cdaar ,(second expr))) )

(define-modf-rewrite cdddar (expr)
  `(cdr (cddar ,(second expr))) )
(define-modf-rewrite cddadr (expr)
  `(cdr (cdadr ,(second expr))) )
(define-modf-rewrite cdaddr (expr)
  `(cdr (caddr ,(second expr))) )
(define-modf-rewrite cadddr (expr)
  `(car (cdddr ,(second expr))) )

(define-modf-rewrite cddddr (expr)
  `(cdr (cdddr ,(second expr))) )

(define-modf-rewrite first (expr)
  `(car ,(second expr)) )
(define-modf-rewrite second (expr)
  `(cadr ,(second expr)) )
(define-modf-rewrite third (expr)
  `(caddr ,(second expr)) )
(define-modf-rewrite fourth (expr)
  `(cadddr ,(second expr)) )
(define-modf-rewrite fifth (expr)
  `(car (cddddr ,(second expr))) )
(define-modf-rewrite sixth (expr)
  `(cadr (cddddr ,(second expr))) )
(define-modf-rewrite seventh (expr)
  `(caddr (cddddr ,(second expr))) )
(define-modf-rewrite eighth (expr)
  `(cadddr (cddddr ,(second expr))) )
(define-modf-rewrite ninth (expr)
  `(car (cddddr (cddddr ,(second expr)))) )
(define-modf-rewrite tenth (expr)
  `(cadr (cddddr (cddddr ,(second expr)))) )

(define-modf-rewrite rest (expr)
  `(cdr ,(second expr)) )
  
